<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRx2HdxE\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRx2HdxE/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerRx2HdxE.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerRx2HdxE\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerRx2HdxE\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'Rx2HdxE',
    'container.build_id' => '2dfdcfdc',
    'container.build_time' => 1762854233,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRx2HdxE');
